name: Portfolio

on:
  push:
    branches:   
      - main
      - form
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Check-health:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run : npm install
      - name : Build project
        run : npm run build
      
      - run: Successfully built
      



