name: Portfolio

on:
  push:
    branches:   
      - main
      - form
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  Check-health:
    runs-on: ubuntu-latest
    steps:
      - name: HTML Validation
        run : npx htmlhint "../Frontend/*.html" 
      
      - run: echo "All good"




